# prueba 1
class calculadora:
    def valor(self):
        #se fuerza el error 
        return 2